export const cocEquipmentImages = {
  "Archer Puppet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787321591/Hero_Equipment_AQ_Archer_Puppet_yal0bi.webp",
  "Frozen Arrow": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324418/Hero_Equipment_AQ_Frozen_Arrow_kmm61e.webp",
  "Giant Arrow": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324456/Hero_Equipment_AQ_Giant_Arrow_xzevcg.webp",
  "Healer Puppet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324502/Hero_Equipment_AQ_Healer_Puppet_bevejb.webp",
  "Invisibility Vial": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324541/Hero_Equipment_AQ_Invisibility_Vial_c8e32b.webp",
  "Magic Mirror": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324582/Hero_Equipment_AQ_Magic_Mirror_ff8jbs.webp",
  "Monolith Arrow": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324617/Hero_Equipment_AQ_MonolithArrow_j1y8ph.webp",
  "Action Figure": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324828/Hero_Equipment_AQ_WWEActionFigure_ajrgjn.webp",
  "Barbarian Puppet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324889/Hero_Equipment_BK_Barbarian_Puppet_befetp.webp",
  "Earthquake Boots": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324919/Hero_Equipment_BK_Earthquake_Boots_axvfuf.webp",
  "Rage Vial": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787324952/Hero_Equipment_BK_Rage_Vial_oij6f1.webp",
  "Snake Bracelet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325014/Hero_Equipment_BK_SnakeBracelet_vsgruy.webp",
  "Spiky Ball": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325049/Hero_Equipment_BK_Spiky_Ball_mgs3pz.webp",
  "Vampstache": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325085/Hero_Equipment_BK_Vampstache_ypz4mp.webp",
  "Giant Gauntlet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325111/Hero_Equipment_BQ_Giant_Gauntlet_q6pzi6.webp",
  "Eternal Tome": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325143/Hero_Equipment_GW_Eternal_Tome_cz65j9.webp",
  "Fireball": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325191/Hero_Equipment_GW_Fireball_qotjfz.webp",
  "Healing Tome": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325225/Hero_Equipment_GW_Healing_Tome_xyilmz.webp",
  "Life Gem": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325263/Hero_Equipment_GW_Life_Gem_p4qvn2.webp",
  "Rage Gem": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325296/Hero_Equipment_GW_Rage_Gem_ldxctx.webp",
  "Dark Orb": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325331/Hero_Equipment_MP_DarkOrb_kmvv7m.webp",
  "Henchmen Puppet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325362/Hero_Equipment_MP_Henchman_ity4e2.webp",
  "Noble Iron": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325402/Hero_Equipment_MP_PowerPump_dhew5f.webp",
  "Electro Boots": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325545/Hero_Equipment_RC_ElectroBoots_bckh3j.webp",
  "Frost Flake": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325580/Hero_Equipment_rc_frost_flake_aponxp.webp",
  "Haste Vial": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325610/Hero_Equipment_RC_Haste_Vial_dzjd1w.webp",
  "Hog Rider Puppet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325709/Hero_Equipment_RC_Hog_Rider_Doll_mehprd.webp",
  "Royal Gem": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325747/Hero_Equipment_RC_Royal_Gem_bohu9g.webp",
  "Seeking Shield": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325789/Hero_Equipment_RC_Seeking_Shield_ce3ygv.webp",
  "Metal Pants": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325834/HeroEquipment_MP_IronPants_vzriwl.webp",
  "Stick Horse": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325904/HeroGear_BK_StickFireHorse_y1kebq.webp",
  "Heroic Torch": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787325945/HeroGear_GW_Olympic_Torch_hh0000_qxnltw.webp",
  "Dark Crown": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326382/HeroGear_MP_DarkCrown_2k_epjyte.webp",
  "Meteor Staff": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326475/HeroGear_MP_MeteoriteSceptre_vkafso.webp",
  "Rocket Spear": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326594/HeroGear_RoyalChampion_RocketSpear_Equipment_03_vvx1d6.webp",
  "Rocket Backpack": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326636/HG_DD_DeadlyDash_Marketing_t2u7az.webp",
  "Electro Fangs": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326676/HG_DD_Electro_Fangs_kh5sjo.webp",
  "Flame Blower": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326705/HG_DD_FlameBreath_Marketing_fhgr8a.webp",
  "Fire Hearth": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326742/HG_DD_FlameHeart_Marketing_cqhmld.webp",
  "Revenge Deck": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326792/HG_DD_reverse_card_qte8vq.webp",
  "Stun Blaster": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326821/HG_DD_StunBlast_Marketing_tgjuhp.webp",
  "Lavaloon Puppet": "https://res.cloudinary.com/dumyctcbe/image/upload/v1787326855/icon_gear_GW_LavaloonPuppet_odrmw0.webp",
};
