export const spellsContext = `
Data Mantra Clash of Clans (Hitung berapa jumlah mantra yang bisa dibawa sebelum membuat komposisi, jangan mention level mantra, cukup sebutkan nama mantra dan kapasitasnya):
- Lightning Spell (Kapasitas: 1 Ruang): Mantra Elixir pertama yang terbuka di Spell Factory level 1. Menyambar petir ke area kecil untuk menghancurkan bangunan pertahanan musuh (terutama Air Defense) dan menyetrum pasukan bertahan.
- Healing Spell (Kapasitas: 2 Ruang): Mantra penyembuh yang terbuka di Spell Factory level 2. Membuat cincin stasioner di tanah yang memulihkan HP semua pasukan ramah yang berada di dalam radiusnya secara bertahap.
- Rage Spell (Kapasitas: 2 Ruang): Mantra amarah yang terbuka di Spell Factory level 3. Menciptakan lingkaran ungu yang meningkatkan kecepatan bergerak dan daya rusak (Damage) pasukan di dalamnya secara signifikan.
- Jump Spell (Kapasitas: 2 Ruang): Mantra lompat yang terbuka di Spell Factory level 4. Membuat jalur lingkaran hijau yang memungkinkan semua pasukan darat melompati tembok pembatas musuh tanpa harus menghancurkannya.
- Freeze Spell (Kapasitas: 1 Ruang): Mantra pembeku yang terbuka di Spell Factory level 5. Membekukan bangunan pertahanan musuh, jebakan, maupun pasukan bertahan di area target untuk menghentikan serangan mereka sementara waktu.
- Clone Spell (Kapasitas: 3 Ruang): Mantra pengganda yang terbuka di Spell Factory level 6. Menciptakan lingkaran pembuat salinan yang akan menduplikat pasukan ramah yang memasuki areanya hingga batas kapasitas tertentu.
- Invisible Spell (Kapasitas: 1 Ruang): Mantra tembus pandang yang terbuka di Spell Factory level 7. Membuat segala sesuatu di areanya (termasuk pasukan ramah, bangunan musuh, kecuali tembok) menjadi tidak terlihat dan tidak bisa ditargetkan selama beberapa detik.
- Recall Spell (Kapasitas: 2 Ruang): Mantra Elixir yang terbuka di Spell Factory level 8. Mampu menarik kembali (teleportasi) pasukan, Hero, dan Pet yang sudah diturunkan di medan perang ke dalam barisan army bar penyerang agar bisa diturunkan ulang di lokasi lain.
- Revive Spell (Kapasitas: 2 Ruang): Mantra kebangkitan yang terbuka di Spell Factory level 9. Memunculkan ikon jantung emas di atas Hero yang telah tumbang, mengizinkan pemain menghidupkan kembali Hero tersebut langsung di medan tempur dengan persentase HP tertentu.
- Totem Spell (Kapasitas: 2 Ruang): Mantra Elixir taktis terbaru yang memancarkan energi magis stasioner untuk memperkuat atau memodifikasi atribut pertarungan pasukan ramah yang melintas di dalam radius areanya.

- Poison Spell (Kapasitas: 1 Ruang): Mantra racun pertama yang terbuka di Dark Spell Factory level 1. Mengurangi kecepatan dan menguras HP pasukan bertahan, Hero, maupun Ground/Air Skeletons musuh yang terjebak di dalamnya.
- Earthquake Spell (Kapasitas: 1 Ruang): Mantra gempa bumi yang terbuka di Dark Spell Factory level 2. Mengguncang tanah untuk merusak infrastruktur bangunan, dan mampu langsung menghancurkan kombinasi 4 Tembok (Walls) musuh berlevel berapa pun jika terkena 4 mantra sekaligus.
- Haste Spell (Kapasitas: 1 Ruang): Mantra percepatan yang terbuka di Dark Spell Factory level 3. Meningkatkan kecepatan bergerak pasukan secara drastis dalam radius kecil tanpa memberikan bonus peningkatan damage seperti Rage Spell.
- Skeleton Spell (Kapasitas: 1 Ruang): Mantra tengkorak yang terbuka di Dark Spell Factory level 4. Memunculkan barisan pasukan tengkorak kecil langsung di lokasi mana pun pada peta untuk mengalihkan perhatian pertahanan musuh.
- Bat Spell (Kapasitas: 1 Ruang): Mantra kelelawar yang terbuka di Dark Spell Factory level 5. Memanggil sekelompok kelelawar terbang yang bergerak cepat dengan target favorit bangunan pertahanan (Defenses) musuh.
- Overgrowth Spell (Kapasitas: 2 Ruang): Mantra pertumbuhan tanaman yang terbuka di Dark Spell Factory level 6. Membekukan dan membuat bangunan musuh di dalam areanya tidak bisa diserang sekaligus tidak bisa menyerang, memaksa pasukan penyerang mengabaikan bangunan tersebut dan berjalan melewatinya.
- Ice Block Spell (Kapasitas: 1 Ruang): Mantra pembeku Dark Elixir yang terbuka di Dark Spell Factory level 7. Menyelubungi pasukan kita dengan lapisan es pelindung, memberikan ketahanan terhadap serangan fatal pertahanan berat musuh (seperti Monolith atau Inferno Tower).
- Angry Spell (Kapasitas: 1 Ruang): Mantra amarah gelap yang terbuka di Dark Spell Factory level 8 (TH15). Memiliki radius luas yang memaksa semua unit pasukan atau Hero yang melintas di dalamnya untuk langsung mengubah target favorit mereka menjadi bangunan pertahanan (Defenses) musuh selama durasi tertentu.
`;
